// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  content2: any;
  web: any;
  cli: any;
  brand: string;
  content: string;
  desc: string;
  homeDiv: string;
  pc: string;
  phone: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
