// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  leftDiv: any;
  footer: any;
  column: string;
  icon: string;
  iconWrap: string;
  item: string;
  label: string;
  link: string;
  meta: string;
}
export const cssExports: CssExports;
export default cssExports;
